### ISSUE TITLE
benutzerdefinierte Server

### ISSUE THREAD

**Issue by alex1702** [scoute-dich/HHSMoodle#1]
Hi, meine schule setzt auch moddle ein. könnte man es vllt machen, dass man die server url einstellen kann?

**Comment by alex1702** [comment]
Oder besser forken und anpassen an meine Schule?

**Comment by scoute-dich** [comment]
Die App ist schon sehr auf meine Schule zugeschnitten. Wenn man die url anpassbar macht, sollte man auch die Bilder über den Liegen neutral gestalten.

**Comment by scoute-dich** [comment]
Sehen eigentlich alle Moodle Urls so aus: 

"https://url.der. moodleinstanz/moodle/..."

**Comment by scoute-dich** [comment]
Dann könnte ich das einrichten. Würde allerdings eine Zeit dauern, da bei uns jetzt die Ferien zu Ende gehen und ich noch einiges für die Schule machen muss. Wenn dir das zu lange dauert, kannst du jederzeit einen Fork erstellen. 

Aber ich denke, wenn ich das nächste mal Zeit habe, setze ich mich dran...

**Comment by alex1702** [comment]
Ok danke also es geht um anpassen auf mehrere Schulen?
Denke ich mach ein fork um das ganze schonmal auszuprobieren und jenachdem kann ich ja ein port anfangen, falls ich die zeit finde.
Sag mal du hast nicht zufällig schon vor eine Open source Stundenplan app zu erstellen oder?
hast du eigentlich jabber?
Schade gibt keine privaten Nachrichten bei Github?!

**Comment by scoute-dich** [comment]
_Wir sind scheunbar beide bei Diaspora. habe dich zu meinen Kontakten hinzugefügt. Hier der Link zu meinem Profil:
scoute_dich@pod.geraspora.de

dann können wir dort Nachrichten austauschen._

Ich habe mir gedacht, die den startbildschirm zu erweitern, dass eine individuelle url eingegeben werden kann.
 und dann entsprechend die Fragmente/Aktivitäten/Einstellungen anpassen. Zusätzlich würde ich die "Header-Bilder" der Listen etwas neutraler gestalten (alles Bilder unserer Schule), falls der Link nicht auf unser Moodle verweist.

Grüße
Gaukler Faun

**Comment by alex1702** [comment]
ah ok hatte mal so grob versucht es umzumünzen und hab überall die url ersetzt...erster versuch fehlgeschlagen xD
ich weiß nicht obs drin ist aber es muss unbedingt deaktiviert werden, dass die ssl zertifikate in ordnung sein müssen. nicht jede schule ist intelligent...
und ich weiß nicht ob das nicht vllt stört. hatte noch nicht debugt.

**Comment by m-schaub** [comment]
Hey,

Es wäre großartig deine App auch für andere Moodle Instanzen nutzen zu können. 
Ich habe leider noch nicht genug programmier Kenntnisse um mich damit zu beschäftigen.

Die URL der Moodle Instanz der Uni Heidelberg sieht wie folgt aus:
https://elearning2.uni-heidelberg.de/
https://elearning2.uni-heidelberg.de/course/index.php

Grüße, 
Matthias

**Comment by scoute-dich** [comment]
I think it should be possible. The problem is, as said before, in the app there are many things only concerning our school (email addresses, school homepage, schedule, pictures). So of I would open the app for other Moodle systems, I have to implement settings for all these things. At the moment I don't have the time for that.

Have you tried other Moodle apps?

Regards
Gaukler Faun
